version: '3.9'

services:
  codingreflex: # Name of the service
    build: .  # Build the image from the current directory
    image: renil-portfolio-service:0.0.1-SNAPSHOT
    env_file:
      - .env
    ports:
      - "8083:8083"  # Map container port 8083 to host port 8083
    environment:
      JAVA_OPTS: -Xms512m -Xmx1024m
      TZ: Asia/Kolkata
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
        - SPRING_DATASOURCE_USERNAME=myuser
        - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - db  # Ensure database is started first
    networks:
      - renil-algo

  db:
    image: postgres:16  # Use a supported PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: renilalgo
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data
    networks:
      - renil-algo


networks:
  renil-algo:
    driver: bridge

volumes:
  postgres-data:
