version: '3.9'

services:
  codingreflex:
    build: .
    image: renil-portfolio-service:0.0.1-SNAPSHOT
    env_file:
      - .env
    ports:
      - "8083:8083"
      - "5005:5005"  # Expose port 5005 for debugging
    environment:
      JAVA_OPTS: -Xms512m -Xmx1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      TZ: Asia/Kolkata
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/renilalgo
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=adminpassword
    depends_on:
      - db
    networks:
      - renil-algo

  db:
    image: postgres:16  # Use a supported PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: renilalgo
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /Users/maulikdave/Projects/renil-portfolio-service:/export
    networks:
      - renil-algo


networks:
  renil-algo:
    driver: bridge

volumes:
  postgres-data:
